--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/03/2020 11:51:47
-- Server version: 5.5.5-10.1.40-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE practica4yii_poo;

--
-- Drop table `marcadores`
--
DROP TABLE IF EXISTS marcadores;

--
-- Set default database
--
USE practica4yii_poo;

--
-- Create table `marcadores`
--
CREATE TABLE IF NOT EXISTS marcadores (
  id int(11) NOT NULL AUTO_INCREMENT,
  enlace varchar(255) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  descripcion_corta varchar(255) DEFAULT NULL,
  descripcion_larga varchar(4096) DEFAULT NULL,
  tipo enum ('Publico', 'Privado') DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_spanish_ci;

-- 
-- Dumping data for table marcadores
--
INSERT INTO marcadores VALUES
(1, 'google', 'https://www.google.es', 'Buscador de internet', 'Es el más usado en el mundo', 'Publico'),
(2, 'Netflix', 'https://www.netflix.com/es/', 'Video en streaming', 'Todas las películas y series que desees, y mucho más.', 'Publico'),
(3, 'Youtube', 'https://www.youtube.com/?hl=es&gl=ES', 'Youtube', 'Obtén tu plan familiar. YouTube Music sin anuncios y en segundo plano para 6 familiares.', 'Privado'),
(4, 'Yii2', 'https://www.yiiframework.com/', 'Framewok libre', '<h1>Yes, it is!</h1>\r\n<p>\r\n   Yii is a fast, secure, and efficient PHP framework.<br>\r\n   Flexible yet pragmatic. <br>\r\n   Works right out of the box. <br>\r\n   Has reasonable defaults.\r\n</p>', 'Privado');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;